# Generated by Django 4.2.4 on 2023-09-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TeleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('username', models.CharField(max_length=200, verbose_name='Юзернейм')),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=3000, verbose_name='Текст вопроса')),
                ('picture', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('picture_file_id', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('answer_content', models.TextField(verbose_name='Ответ')),
                ('answer_picture', models.ImageField(blank=True, null=True, upload_to='photos/answers/%Y/%m/%d', verbose_name='Изображение к ответу')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.questionstatus', verbose_name='Статус')),
                ('teleuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.teleuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопрос',
            },
        ),
    ]
