# Generated by Django 4.2.4 on 2023-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_teleuser_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleuser',
            name='telegram_user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
