# Generated by Django 4.2.4 on 2023-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereview',
            name='content',
            field=models.TextField(default=False, verbose_name='Текст отзыва'),
        ),
    ]
