# Generated by Django 4.2.4 on 2023-08-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_storereview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=False),
        ),
        migrations.AlterField(
            model_name='storereview',
            name='content',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
    ]
