# Generated by Django 4.2.4 on 2023-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_brand_slug_alter_storereview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=False),
        ),
        migrations.AlterField(
            model_name='opersystem',
            name='slug',
            field=models.SlugField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='slug',
            field=models.SlugField(default=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='slug',
            field=models.SlugField(default=False),
        ),
    ]
