# Generated by Django 4.2.4 on 2023-08-24 11:26

from django.db import migrations, models
import shop.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_item_slug_alter_opersystem_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['title'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производитель'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['pk'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='opersystem',
            options={'ordering': ['title'], 'verbose_name': 'Операционная система', 'verbose_name_plural': 'Операционная система'},
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='2344@mail.com', max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=shop.utilities.get_path_image, verbose_name='Изображение'),
        ),
    ]
