# Generated by Django 4.2.4 on 2023-08-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_review_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='', verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='to_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='shop.review'),
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.buyer', verbose_name='Покупатель')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.item', verbose_name='Товар')),
            ],
        ),
    ]
