# Generated by Django 4.2.4 on 2023-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_review_options_alter_review_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'введите корректный адрес электронной почты'}, max_length=254, verbose_name='Электронная почта'),
        ),
    ]
