# Generated by Django 4.2.4 on 2023-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_review_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='amount',
            field=models.SmallIntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
