# Generated by Django 4.2.4 on 2023-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_favoriteitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(default='', max_length=2000, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
