# Generated by Django 4.2.4 on 2023-08-30 12:15
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orderitem_created'),
    ]

    operations = [
        CreateExtension('pg_trgm'),
        migrations.AlterModelOptions(
            name='favoriteitem',
            options={'ordering': ['-pk'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-pk'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pk'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'ordering': ['-pk'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='storereview',
            options={'ordering': ['-pk'], 'verbose_name': 'Отзыв о компании', 'verbose_name_plural': 'Отзывы о компании'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='shop.orderstatus', verbose_name='Статус'),
        ),
    ]
