# Generated by Django 4.2.4 on 2023-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_favoriteitem_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комментарий'),
        ),
    ]
